### ISSUE TITLE
Makefile refactor

### ISSUE THREAD

**Issue by MichaelCurrin** [ironpeakservices/iron-go-project#30]
Hi I want to suggest some changes to Makefile

The mkdir bit can come out as from my own project testing I found I didn't need it. Go build makes the dir.

```mk
build:
	mkdir -p dist/
	CGO_ENABLED=0 go build -ldflags '-w -s -extldflags "-static"' -o dist/app ./cmd
```

---

My run command in Makefile uses go. 

```mk
run:
    go run main.go
```

But eith your command you have to always make sure your binary is up to date first.

```mk
run:
	./dist/app
```

---

I don't think this does anything as is:

```mk
clean:
    rm -r dist || true
```

`rm -r` will complain it can't delete dist if its not empty. 

And rm returns success even if there is nothing to delete, based on my light testing.

therefore I always do `rm -rf` for local and make use as it forces to delete.

```mk
clean:
    rm -rf dist
```

**Comment by hazcod** [comment]
Done in https://github.com/ironpeakservices/iron-go-project/commit/feae3477b74b2a44697880ef5bf3197ff5c3b2c7 , thanks!

**Comment by MichaelCurrin** [comment]
Thanks.

I don't this will work though:

```mk
run:
	go run ./dist/
```

Which is running go on directory with a binary file.

--

My suggestion above was to use **go** to run a script.

Here as two commands in case you wanted both:

```mk
dev:
  go run main.go

run:
  dist/app
```

Or instead of `dev` and `run`, use `run` and `app` or something.
