### ISSUE TITLE
Add use template badge

### ISSUE THREAD

**Issue by MichaelCurrin** [ironpeakservices/iron-go-project#31]
I use my badge generator tool to make a markdown badge

Add your repo details and tick template checkbox, then copy the markdown snippet bit to your readme.

https://michaelcurrin.github.io/badge-generator/#/repo

**Comment by MichaelCurrin** [comment]
Sample

<div align="center">

[![Use this template](https://img.shields.io/badge/Generate-Use_this_template-2ea44f?style=for-the-badge)](https://github.com/MichaelCurrin/badge-generator/generate)

</div>

**Comment by hazcod** [comment]
Hi @MichaelCurrin , thank you for the suggestion but since this is already provided by GitHub natively, I'm closing this one.

![image](https://user-images.githubusercontent.com/5222512/107927561-75053900-6f77-11eb-86e8-0fb82cfd4f1a.png)
